### ISSUE TITLE
wx._core.PyAssertionError: C++ assertion ok failed at ../src/unix/glx11.cpp(442) in GetGLXVersion(): GLX version not found

### ISSUE THREAD

**Issue by rxseger** [rxseger/linuxproblems#3]
Raspberry Pi 3 with Raspbian OS 2016-05-27-raspbian-jessie.img
[Headless setup](https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=74176) and VNC
sudo apt install gnuradio
sudo apt install gr-osmosdr
gnuradio-companion
Generate, or run `python top_block.py` after generating

```
:~ $ python top_block.py 
linux; GNU C++ version 4.9.1; Boost_105500; UHD_003.007.003-0-unknown

Xlib:  extension "RANDR" missing on display ":2.0".
Using Volk machine: neon_hardfp_orc
Traceback (most recent call last):
  File "top_block.py", line 211, in <module>
    main()
  File "top_block.py", line 205, in main
    tb = top_block_cls()
  File "top_block.py", line 114, in __init__
    peak_hold=False,
  File "/usr/lib/python2.7/dist-packages/gnuradio/wxgui/fftsink_gl.py", line 126, in __init__
    persist_alpha=persist_alpha,
  File "/usr/lib/python2.7/dist-packages/gnuradio/wxgui/fft_window.py", line 277, in __init__
    self.plotter = plotter.channel_plotter(self)
  File "/usr/lib/python2.7/dist-packages/gnuradio/wxgui/plotter/channel_plotter.py", line 49, in __init__
    grid_plotter_base.__init__(self, parent, MIN_PADDING)
  File "/usr/lib/python2.7/dist-packages/gnuradio/wxgui/plotter/grid_plotter_base.py", line 50, in __init__
    plotter_base.__init__(self, parent)
  File "/usr/lib/python2.7/dist-packages/gnuradio/wxgui/plotter/plotter_base.py", line 94, in __init__
    wx.glcanvas.GLCanvas.__init__(self, parent, wx.ID_ANY, attribList=attribList);  # Specifically use the CTOR which does NOT create an implicit GL context
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/glcanvas.py", line 106, in __init__
    _glcanvas.GLCanvas_swiginit(self,_glcanvas.new_GLCanvas(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "ok" failed at ../src/unix/glx11.cpp(442) in GetGLXVersion(): GLX version not found
```

**Comment by rxseger** [comment]
http://www.rs-online.com/designspark/electronics/eng/blog/taking-the-raspberry-pi-2-for-a-test-drive-with-gnu-radio-2

> Posted by lukbe at 09:04 on 05/10/2015
> ./src/unix/glx11.cpp(442) in GetGLXVersion(): GLX version not found
> 
> I had this problem too,solutions: sudo apt-get install libgl1-mesa-swx11

fixes the problem, but hit another error (also mentioned there), with the audio sink:

https://github.com/rxseger/linuxproblems/issues/4 gr::log :ERROR: audio_alsa_sink0 - [default]: set_channels failed: Invalid argument
